### Alpha Vantage

https://www.alphavantage.co/documentation/

#### Pegando cotações semanais - JSON

In [11]:
import requests
chave_api ='ROK04RYWBLCBQR6G'

import requests

# replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
url = f'https://www.alphavantage.co/query?function=TIME_SERIES_WEEKLY_ADJUSTED&symbol=IBM&apikey={chave_api}'
r = requests.get(url)
data = r.json()

print(data['Meta Data'])

{'1. Information': 'Weekly Adjusted Prices and Volumes', '2. Symbol': 'IBM', '3. Last Refreshed': '2026-05-11', '4. Time Zone': 'US/Eastern'}

#### Pegando cotações semanais - CSV

In [12]:
import pandas as pd
from io import StringIO
# replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
url = f'https://www.alphavantage.co/query?function=TIME_SERIES_WEEKLY_ADJUSTED&symbol=IBM&apikey={chave_api}&datatype=csv'
r = requests.get(url)
tabela = pd.read_csv(StringIO(r.text))

display(tabela)

,timestamp,open,high,low,close,adjusted close,volume,dividend amount
0,2026-05-11,228.66,230.23,222.55,223.55,223.5500,6677186,0.00
1,2026-05-08,232.00,234.09,224.38,229.76,229.7600,26716501,1.69
2,2026-05-01,229.95,235.95,224.90,232.20,230.5045,29532709,0.00
3,2026-04-24,255.00,258.50,221.73,231.98,230.2861,55047502,0.00
4,2026-04-17,233.63,255.65,231.70,253.47,251.6192,23495380,0.00
...,...,...,...,...,...,...,...,...
1379,1999-12-10,113.00,122.12,107.56,109.00,53.1750,58626000,0.00
1380,1999-12-03,104.94,112.87,102.12,111.87,54.5751,37670000,0.00
1381,1999-11-26,105.50,109.87,101.81,105.00,51.2236,37165600,0.00
1382,1999-11-19,96.00,105.12,92.62,103.94,50.7065,61550800,0.00
1383,1999-11-12,90.50,97.50,90.50,95.87,46.7696,43569700,0.12

### Cotações

In [ ]:
# PEgando várias cotações de uma vez
acoes = ['ITUB4', 'ABEV3', 'BBAS3']

compilada = pd.DataFrame()

for acao in acoes:
    # Cotações do Itaú
    url = f'https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol={acao}.SAO&apikey={chave_api}&datatype=csv'
    r = requests.get(url)
    tabela = pd.read_csv(StringIO(r.text))
    lista_tabelas = [compilada, tabela]
    compilada = pd.concat(lista_tabelas)

display(compilada)

### Encontrar ativos

In [ ]:
# Encontrando os ativos pelo nome da empresa
url = f'https://www.alphavantage.co/query?function=SYMBOL_SEARCH&keywords=itau&apikey={chave_api}&datatype=csv'
r = requests.get(url)
tabela = pd.read_csv(StringIO(r.text))

display(tabela)

,symbol,name,type,region,marketOpen,marketClose,timezone,currency,matchScore
0,ITUB,Itau Unibanco Holding S.A.,Equity,United States,09:30,16:00,UTC-04,USD,0.7500
1,ISTT11.SAO,Itau Isento Setembro 29 Fundo De Investimento ...,Mutual Fund,Brazil/Sao Paolo,10:00,17:30,UTC-03,BRL,0.4615
2,ITRI11.SAO,Itau Total Return Fundo De Investimento Imobil...,Mutual Fund,Brazil/Sao Paolo,10:00,17:30,UTC-03,BRL,0.4615
3,IFRA11.SAO,Itau FIC De Fundos De Investimento Em Direitos...,ETF,Brazil/Sao Paolo,10:00,17:30,UTC-03,BRL,0.3077
4,IFRI11.SAO,Itau Fundo De Investimento Em Cotas De FIDIFEI...,Mutual Fund,Brazil/Sao Paolo,10:00,17:30,UTC-03,BRL,0.3077
5,TMPS11.SAO,Itau Tempus Fundo De Investimento Imobiliario,Equity,Brazil/Sao Paolo,10:00,17:30,UTC-03,BRL,0.3077
6,RURA11.SAO,Itau Asset Rural Fiagro - Imobiliario,ETF,Brazil/Sao Paolo,10:00,17:30,UTC-03,BRL,0.1951

### Informações de Resultado

In [ ]:
# replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
url = f'https://www.alphavantage.co/query?function=SHARES_OUTSTANDING&symbol=AMZN&apikey={chave_api}'
r = requests.get(url)
data = r.json()

print(data)

{'symbol': 'AMZN', 'status': 'success', 'data': [{'date': '2026-03-31', 'shares_outstanding_diluted': '10874000000', 'shares_outstanding_basic': '10874000000'}, {'date': '2025-12-31', 'shares_outstanding_diluted': '10863000000', 'shares_outstanding_basic': '10863000000'}, {'date': '2025-09-30', 'shares_outstanding_diluted': '10845000000', 'shares_outstanding_basic': '10845000000'}, {'date': '2025-06-30', 'shares_outstanding_diluted': '10806000000', 'shares_outstanding_basic': '10806000000'}, {'date': '2025-03-31', 'shares_outstanding_diluted': '10793000000', 'shares_outstanding_basic': '10603000000'}, {'date': '2024-12-31', 'shares_outstanding_diluted': '10769000000', 'shares_outstanding_basic': '10551000000'}, {'date': '2024-09-30', 'shares_outstanding_diluted': '10735000000', 'shares_outstanding_basic': '10501000000'}, {'date': '2024-06-30', 'shares_outstanding_diluted': '10708000000', 'shares_outstanding_basic': '10447000000'}, {'date': '2024-03-31', 'shares_outstanding_diluted': '10670000000', 'shares_outstanding_basic': '10393000000'}, {'date': '2023-12-31', 'shares_outstanding_diluted': '10612000000', 'shares_outstanding_basic': '10358000000'}, {'date': '2023-09-30', 'shares_outstanding_diluted': '10558000000', 'shares_outstanding_basic': '10322000000'}, {'date': '2023-06-30', 'shares_outstanding_diluted': '10449000000', 'shares_outstanding_basic': '10285000000'}, {'date': '2023-03-31', 'shares_outstanding_diluted': '10347000000', 'shares_outstanding_basic': '10250000000'}, {'date': '2022-12-31', 'shares_outstanding_diluted': '10222000000', 'shares_outstanding_basic': '10222000000'}, {'date': '2022-09-30', 'shares_outstanding_diluted': '10331000000', 'shares_outstanding_basic': '10191000000'}, {'date': '2022-06-30', 'shares_outstanding_diluted': '10175000000', 'shares_outstanding_basic': '10175000000'}, {'date': '2022-03-31', 'shares_outstanding_diluted': '509000000', 'shares_outstanding_basic': '509000000'}, {'date': '2021-12-31', 'shares_outstanding_diluted': '518000000', 'shares_outstanding_basic': '509000000'}, {'date': '2021-09-30', 'shares_outstanding_diluted': '515000000', 'shares_outstanding_basic': '507000000'}, {'date': '2021-06-30', 'shares_outstanding_diluted': '514000000', 'shares_outstanding_basic': '505000000'}, {'date': '2021-03-31', 'shares_outstanding_diluted': '513000000', 'shares_outstanding_basic': '504000000'}, {'date': '2020-12-31', 'shares_outstanding_diluted': '513000000', 'shares_outstanding_basic': '502000000'}, {'date': '2020-09-30', 'shares_outstanding_diluted': '512000000', 'shares_outstanding_basic': '501000000'}, {'date': '2020-06-30', 'shares_outstanding_diluted': '509000000', 'shares_outstanding_basic': '500000000'}, {'date': '2020-03-31', 'shares_outstanding_diluted': '506000000', 'shares_outstanding_basic': '498000000'}, {'date': '2019-12-31', 'shares_outstanding_diluted': '505000000', 'shares_outstanding_basic': '496000000'}, {'date': '2019-09-30', 'shares_outstanding_diluted': '504000000', 'shares_outstanding_basic': '495000000'}, {'date': '2019-06-30', 'shares_outstanding_diluted': '503000000', 'shares_outstanding_basic': '493000000'}, {'date': '2019-03-31', 'shares_outstanding_diluted': '502000000', 'shares_outstanding_basic': '491000000'}, {'date': '2018-12-31', 'shares_outstanding_diluted': '501000000', 'shares_outstanding_basic': '490000000'}, {'date': '2018-09-30', 'shares_outstanding_diluted': '501000000', 'shares_outstanding_basic': '488000000'}, {'date': '2018-06-30', 'shares_outstanding_diluted': '500000000', 'shares_outstanding_basic': '486000000'}, {'date': '2018-03-31', 'shares_outstanding_diluted': '498000000', 'shares_outstanding_basic': '484000000'}, {'date': '2017-12-31', 'shares_outstanding_diluted': '496000000', 'shares_outstanding_basic': '483000000'}, {'date': '2017-09-30', 'shares_outstanding_diluted': '494000000', 'shares_outstanding_basic': '481000000'}, {'date': '2017-06-30', 'shares_outstanding_diluted': '492000000', 'shares_outstanding_basic': '479000000'}, {'date': '2017-03-31', 'shares_outstanding_diluted': '490000000', 'shares_outstanding_basic': '477000000'}, {'date': '2016-12-31', 'shares_outstanding_diluted': '486000000', 'shares_outstanding_basic': '476000000'}, {'date': '2016-09-30', 'shares_outstanding_diluted': '485000000', 'shares_outstanding_basic': '474000000'}, {'date': '2016-06-30', 'shares_outstanding_diluted': '483000000', 'shares_outstanding_basic': '473000000'}, {'date': '2016-03-31', 'shares_outstanding_diluted': '481000000', 'shares_outstanding_basic': '471000000'}, {'date': '2015-12-31', 'shares_outstanding_diluted': '481000000', 'shares_outstanding_basic': '470000000'}, {'date': '2015-09-30', 'shares_outstanding_diluted': '478000000', 'shares_outstanding_basic': '468000000'}, {'date': '2015-06-30', 'shares_outstanding_diluted': '476000000', 'shares_outstanding_basic': '467000000'}, {'date': '2015-03-31', 'shares_outstanding_diluted': '465000000', 'shares_outstanding_basic': '465000000'}, {'date': '2014-12-31', 'shares_outstanding_diluted': '472000000', 'shares_outstanding_basic': '464000000'}, {'date': '2014-09-30', 'shares_outstanding_diluted': '463000000', 'shares_outstanding_basic': '463000000'}, {'date': '2014-06-30', 'shares_outstanding_diluted': '461000000', 'shares_outstanding_basic': '461000000'}, {'date': '2014-03-31', 'shares_outstanding_diluted': '468000000', 'shares_outstanding_basic': '460000000'}, {'date': '2013-12-31', 'shares_outstanding_diluted': '467000000', 'shares_outstanding_basic': '458000000'}, {'date': '2013-09-30', 'shares_outstanding_diluted': '457000000', 'shares_outstanding_basic': '457000000'}, {'date': '2013-06-30', 'shares_outstanding_diluted': '456000000', 'shares_outstanding_basic': '456000000'}, {'date': '2013-03-31', 'shares_outstanding_diluted': '463000000', 'shares_outstanding_basic': '455000000'}, {'date': '2012-12-31', 'shares_outstanding_diluted': '462000000', 'shares_outstanding_basic': '455000000'}, {'date': '2012-09-30', 'shares_outstanding_diluted': '460000000', 'shares_outstanding_basic': '452000000'}, {'date': '2012-06-30', 'shares_outstanding_diluted': '458000000', 'shares_outstanding_basic': '451000000'}, {'date': '2012-03-31', 'shares_outstanding_diluted': '460000000', 'shares_outstanding_basic': '453000000'}, {'date': '2011-12-31', 'shares_outstanding_diluted': '462000000', 'shares_outstanding_basic': '455000000'}, {'date': '2011-09-30', 'shares_outstanding_diluted': '461000000', 'shares_outstanding_basic': '454000000'}, {'date': '2011-06-30', 'shares_outstanding_diluted': '460000000', 'shares_outstanding_basic': '453000000'}, {'date': '2011-03-31', 'shares_outstanding_diluted': '459000000', 'shares_outstanding_basic': '451000000'}, {'date': '2010-12-31', 'shares_outstanding_diluted': '458000000', 'shares_outstanding_basic': '450000000'}, {'date': '2010-09-30', 'shares_outstanding_diluted': '456000000', 'shares_outstanding_basic': '448000000'}, {'date': '2010-06-30', 'shares_outstanding_diluted': '455000000', 'shares_outstanding_basic': '447000000'}, {'date': '2010-03-31', 'shares_outstanding_diluted': '454000000', 'shares_outstanding_basic': '445000000'}, {'date': '2009-12-31', 'shares_outstanding_diluted': '450000000', 'shares_outstanding_basic': '440000000'}, {'date': '2009-09-30', 'shares_outstanding_diluted': '441000000', 'shares_outstanding_basic': '432000000'}, {'date': '2009-06-30', 'shares_outstanding_diluted': '440000000', 'shares_outstanding_basic': '431000000'}, {'date': '2009-03-31', 'shares_outstanding_diluted': '437000000', 'shares_outstanding_basic': '429000000'}, {'date': '2008-12-31', 'shares_outstanding_diluted': '435000000', 'shares_outstanding_basic': '429000000'}, {'date': '2008-09-30', 'shares_outstanding_diluted': '436000000', 'shares_outstanding_basic': '427000000'}, {'date': '2008-06-30', 'shares_outstanding_diluted': '430000000', 'shares_outstanding_basic': '420000000'}]}